excluded: # paths to ignore during linting. Takes precedence over `included`.
  - Carthage
  - tpg offline/External

line_length: 130

disabled_rules:
  - function_body_length
  - type_body_length
  - cyclomatic_complexity
  - file_length
  - line_length
